In [44]:
# Dependencies and Setup
import pandas as pd

# File to Load 
file1 = "data/life-expectancy-at-birth-total-years.csv"
file2 = "data/median-age.csv"
file3 = "data/population-density-vs-prosperity.csv"
file4 = "data/urban-and-rural-population.csv"
file6 = "data/urban-vs-rural-majority.csv"

# Read File and store into Pandas data frame
life_expectancy = pd.read_csv(file1)
median_age = pd.read_csv(file2)
density_vs_prosperity = pd.read_csv(file3)
urban_rural_population = pd.read_csv(file4)
urban_vs_rural_majority = pd.read_csv(file6)

FileNotFoundError: [Errno 2] File b'data/life-expectancy-at-birth-total-years.csv' does not exist: b'data/life-expectancy-at-birth-total-years.csv'

In [35]:
density_vs_prosperity.shape

(47234, 6)

In [36]:
urban_rural_population.shape

(15031, 5)

In [37]:
urban_vs_rural_majority.shape

(27977, 5)

In [38]:
# Merge data
merged_data = pd.merge(density_vs_prosperity, urban_rural_population, on=["Entity", "Code", "Year"])
merged_data.shape

(14905, 8)

In [39]:
merged_data = pd.merge(merged_data, urban_vs_rural_majority, on=["Entity", "Code", "Year"])
merged_data.shape

(12340, 10)

In [40]:
# Export CSV
merged_data.to_csv('merged_data_noslums_compact.csv') 

merged_data.head()

,Entity,Code,Year,Population density (people per km² of land area),GDP per capita (constant 2011 international $),Total population (Gapminder),Urban population,Rural population,Urban (%),Rural (%)
0,Afghanistan,AFG,1960,NaN,NaN,8996351.0,755783,8240568,8.401,91.598999
1,Afghanistan,AFG,1961,14.040934,NaN,9166764.0,796042,8370722,8.684,91.316002
2,Afghanistan,AFG,1962,14.315271,NaN,9345868.0,838885,8506983,8.976,91.024002
3,Afghanistan,AFG,1963,14.603367,NaN,9533954.0,884370,8649584,9.276,90.723999
4,Afghanistan,AFG,1964,14.905739,NaN,9731361.0,932848,8798513,9.586,90.414001

In [41]:
merged_data.tail()

,Entity,Code,Year,Population density (people per km² of land area),GDP per capita (constant 2011 international $),Total population (Gapminder),Urban population,Rural population,Urban (%),Rural (%)
12335,Zimbabwe,ZWE,2013,38.915616,1929.765001,15054506.0,4915898,10138608,32.654,67.346001
12336,Zimbabwe,ZWE,2014,39.838891,1925.138698,15411675.0,5009411,10402264,32.504,67.496002
12337,Zimbabwe,ZWE,2015,40.784415,1912.280261,15777451.0,5109528,10667923,32.385,67.614998
12338,Zimbabwe,ZWE,2016,41.748383,1879.628119,16150362.0,5215921,10934441,32.296,67.704002
12339,Zimbabwe,ZWE,2017,42.729492,1899.774977,16529904.0,5328745,11201159,32.237,67.763000

In [43]:
#Format columns
merged_data = merged_data.rename(columns={"Population density (people per km² of land area)": "pop_density",
                                          "GDP per capita (constant 2011 international $)" : "gdp",
                                         "Total population (Gapminder)": "total_pop",
                                         "Urban population": "urban_pop",
                                         "Rural population": "rural_pop",
                                         "Urban (%)":"urban_pct",
                                         "Rural (%)": "rural_pct"})
merged_data.head()

,Entity,Code,Year,pop_density,gdp,total_pop,urban_pop,rural_pop,urban_pct,rural_pct
0,Afghanistan,AFG,1960,NaN,NaN,8996351.0,755783,8240568,8.401,91.598999
1,Afghanistan,AFG,1961,14.040934,NaN,9166764.0,796042,8370722,8.684,91.316002
2,Afghanistan,AFG,1962,14.315271,NaN,9345868.0,838885,8506983,8.976,91.024002
3,Afghanistan,AFG,1963,14.603367,NaN,9533954.0,884370,8649584,9.276,90.723999
4,Afghanistan,AFG,1964,14.905739,NaN,9731361.0,932848,8798513,9.586,90.414001

In [4]:
# Filter by most recent year
merged_data = merged_data[merged_data["Year"] == 2014]
merged_data.head()

,Entity,Code,Year,Population density (people per km² of land area),GDP per capita (constant 2011 international $),Total population (Gapminder),"Estimates, 1950 - 2015: Population density (persons per square km), as of 1 July (persons per square km)",Urban population,Rural population,Urban (%),Rural (%),Urban population living in slums,Urban population not living in slums
0,Afghanistan,AFG,2014,50.176179,1838.960244,32758020.0,50.176179,8054214,24703806,24.587,75.413002,5398133,3211330
6,Angola,AGO,2014,21.593379,6257.152874,26920466.0,21.593379,16887478,10032988,62.731,37.269001,6465507,5184055
15,Argentina,ARG,2014,15.705657,18797.547947,42981515.0,15.705657,39275219,3706296,91.377,8.623000,6575255,32797532
16,Armenia,ARM,2014,102.080084,7971.117928,2906220.0,102.080084,1834174,1072046,63.112,36.888000,262866,1562589
23,Bangladesh,BGD,2014,1224.593063,2973.041565,159405279.0,1224.593063,53456560,105948719,33.535,66.464996,29437876,23988397

In [5]:
# Export CSV
merged_data.to_csv('merged_data.csv')